---
abstract: 'Perl library for rapid publishing of messages on PubNub.com'
author:
  - 'Binary.com <fayland@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PubNub-PubSub
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 5.40
version: v1.1.0
